### ISSUE TITLE
Maps that crash mc2mt

### ISSUE THREAD

**Issue by sbrl** [jonajames/mc2mt#3]
Hello! You asked me to  open an issue about some maps that crash mc2mt. Here are some planetminecraft links:

 - https://www.planetminecraft.com/project/donnerhall-the-nordic-city/
 - https://www.planetminecraft.com/project/grandeena---castle/
 - https://www.planetminecraft.com/project/cair-paravel-3152408/

**Comment by jonajames** [comment]
The tool cannot open nor convert maps before 1.7
Theese seems to be old maps, the problem here is that exactly 0 chunks are being found...
Minecraft should autmatically update maps to the newest version if you open them... could you do that and try again?

**Comment by sbrl** [comment]
Ah, I see. Thanks for the clarification!

I don't own a copy of Minecraft, so I guess I'll have to look for some other maps to take inspiration from :-)
