### ISSUE TITLE
Feature Request - Configurable replacement table

### ISSUE THREAD

**Issue by ACBob** [jonajames/mc2mt#5]
This'd mostly be for those one or two games that don't depend on `default`/`minetest_game` (such as MineClone2).

I'm thinking there'd be some config file, a default one that points to the default mod, and a specifiable one from the command line that would override the default config file.

**Comment by jonajames** [comment]
I have already thought about something like this, but found no ideal solutions.
it's not just about converting the block name but also the block rotation, wich is sometimes different for different blocks.
And in some cases I've just matched and converted a bunch of blocks all together (like slabs stairs, etc).

There are already some mods that can be enabled/disabled, for example:
```
nether_table = {
    "nether_brick_slab" : ("stairs:slab_nether_brick",15,type2facedir),
    "netherrack" : ("nether:rack",0,0),
    "nether_bricks" : ("nether:brick",0,0),
    "nether_brick_fence" : ("nether:fence_nether_brick",0,0),
    "nether_brick_stairs" : ("stairs:stair_nether_brick",0,stair2facedir),
    "glowstone":("nether:glowstone",0,0),
    "nether_quartz_ore" : ("nether:glowstone",0,0),
    "nether_wart_block" : ("nether:sand",0,0),
    "red_nether_bricks" : ("nether:rack",0,0),
    "nether_brick" : ("nether:brick_cube",0,0),
    "nether_portal" : ("nether:portal",15,12),
    "end_portal" : ("nether:portal",15,12),
    "red_nether_brick_stairs" : ("stairs:stair_nether_brick",0,stair2facedir),
    "red_nether_brick_slab" : ("stairs:slab_nether_brick",15,type2facedir),
}
```
This can be enabled using `--enable_nether`

Maybe this could be refactored a bit and used to include many more mods?

If you want to provide a file with the same kind of formt i can try to include it.

**Comment by jonajames** [comment]
You can now specify a json file with the replacements.
