### ISSUE TITLE
Missing info in readme that.. this converter work only on MC 1.7 or newer maps

### ISSUE THREAD

**Issue by Sharpik** [jonajames/mc2mt#6]
Missing info in readme.. that this converter work only on MC 1.7 or newer maps

It took me few hours of editing and testing other libs like "Anvil" to not crash with MC world 1.6.4
Than I get know that this tool wont convert this worlds eather.

But in theory.. It's just about the missing ID convertion table (based on intager IDs) to MT (string name) equivalent?
Because I think that we can add this feature to this converter with not that much work..
And it will be able to convert all MC maps based on Anvil.

Thanks for Your work.

**Comment by jonajames** [comment]
It has basically never been tested with older maps.
If you want to provide a small test map with that version I will try to fix it.
Anyway I have the idea that Anvil-Parser should already (in theory) support ID-based maps. 

I also found this:
https://github.com/matcool/anvil-parser/issues/21

**Comment by jonajames** [comment]
Tested and should be working now.
