### ISSUE TITLE
5x speed increase

### ISSUE THREAD

**Issue by talamh** [jonajames/mc2mt#7]
jonajames I've stumbled across your converter again, last time i saw it was when you posted on the forums because you were having an issue with param2's. I forked your repo and added the dependencies needed to get mc2mt running using pypy3 and experimented with using the nuitka compiler. Found a bit of a complicated build process that got me a 5x speed increase don't know if it will be of any use or interest to you but here's the repo https://github.com/talamh/mc2mt

**Comment by jonajames** [comment]
I'm not really a fan of static dependencies, so that's a no-go for me.
But the need for speed improvement is there and there's a lot that can be done in that sense... I'll look into it.
=)

**Comment by jonajames** [comment]
I did some optimization here and there.
The largest amount of time is actually spent in the anvil library so that's the bottleneck.
I may add a note in the readme
